apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - image: tobi312/rpi-mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            # Change this password!
            value: yourpassword
        ports:
        - containerPort: 3306
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql
