apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: armhf/redis:3.2
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 1.0
            memory: 1048Mi
          requests:
            cpu: 0.5
            memory: 512Mi
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    spring-cloud-service: redis
spec:
  ports:
    - port: 6379
  selector:
    name: redis
